# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false
  #All roles in one
    config.vm.define "lb1" do |lb|
      lb.vm.hostname = "lb1"
      lb.vm.network :private_network, ip: "192.168.1.21"
      #running ansible against all hosts as part of last provsioning job
      config.vm.network "forwarded_port", guest: 80, host: 8080
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../site.yml"
        ansible.sudo = true
        ansible.limit = 'all'# "#{info[:ip]}" # Ansible hosts are identified by ip
        ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
        ansible.groups = {
          "web" => ["lb1"],
          "app" => ["lb1"],
          "lb" => ["lb1"],
          "all_groups:children" => ["web", "lb", "app"]
        }
      end
    end
end
