# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  #Web servers
  config.vm.define "web1" do |web|
    web.vm.hostname = "web1"
    web.vm.network :private_network, ip: "192.168.1.11"
  end

  #Load Balancers
  config.vm.define "lb1" do |lb|
    lb.vm.hostname = "lb1"
    lb.vm.network :private_network, ip: "192.168.1.21"
  end

  #Appservers
  config.vm.define "app1" do |app|
    app.vm.hostname = "app1"
    app.vm.network :private_network, ip: "192.168.1.31"
  end

  # Provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../site.yml"
    ansible.sudo = true
    ansible.groups = {
      "web" => ["web"],
      "lb1" => ["lb"],
      "app1" => ["app"],
      "all_groups:children" => ["web", "lb", "app"]
    }
  end

end
